plan
fogo-sh/distributed-library pull request #1
Opened 2022-10-03 20:41 UTC by jackharrhy

feel free to comment on plan

2022-10-03 21:43 UTC, nint8835 requested changes

2022-10-03 21:43 UTC, nint8835 commented on README.md
> +  - reading this file, and playing the actions, you can bascially reach the current 'state' of the library
```suggestion
  - reading this file, and playing the actions, you can basically reach the current 'state' of the library
```

2022-10-03 21:43 UTC, nint8835 commented on README.md
> +your friends have books, therefore you do too books
```suggestion
your friends have books, therefore you do too
```

2022-10-03 22:40 UTC, lilmert commented
what would be the expected state for two people adding books same time? how will the "db" be synced across instances of the library

2022-10-03 23:38 UTC, ranguli commented
finish your other projects first :(

2022-10-14 00:27 UTC, jackharrhy commented
no more go

2022-10-14 00:27 UTC, closed without merging